// <auto-generated />
using System;
using Aplicacao_Kolping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplicacao_Kolping.Migrations
{
    [DbContext(typeof(Aplicacao_KolpingContext))]
    [Migration("20201231141128_AjusteNoUmParaVarios")]
    partial class AjusteNoUmParaVarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aplicacao_Kolping.Models.Alunos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("DiadePagamento");

                    b.Property<string>("Documento");

                    b.Property<string>("Email");

                    b.Property<int?>("ModalidadesId");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("Rua");

                    b.Property<int>("Telefone");

                    b.HasKey("ID");

                    b.HasIndex("ModalidadesId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Modalidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlunosID");

                    b.Property<string>("Name");

                    b.Property<double>("Preco");

                    b.HasKey("Id");

                    b.HasIndex("AlunosID");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Pagamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlunosID");

                    b.Property<DateTime>("Data");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("AlunosID");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Alunos", b =>
                {
                    b.HasOne("Aplicacao_Kolping.Models.Modalidades")
                        .WithMany()
                        .HasForeignKey("ModalidadesId");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Modalidades", b =>
                {
                    b.HasOne("Aplicacao_Kolping.Models.Alunos")
                        .WithMany("Modalidades")
                        .HasForeignKey("AlunosID");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Pagamentos", b =>
                {
                    b.HasOne("Aplicacao_Kolping.Models.Alunos")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AlunosID");
                });
#pragma warning restore 612, 618
        }
    }
}
