// <auto-generated />
using System;
using Aplicacao_Kolping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplicacao_Kolping.Migrations
{
    [DbContext(typeof(Aplicacao_KolpingContext))]
    [Migration("20210110042021_AlteracaoDoTipoTelefone")]
    partial class AlteracaoDoTipoTelefone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aplicacao_Kolping.Models.Alunos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<int>("DiadePagamento");

                    b.Property<string>("Documento");

                    b.Property<string>("Email");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Numero");

                    b.Property<string>("Rua");

                    b.Property<long>("Telefone");

                    b.HasKey("ID");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.AlunosModalidades", b =>
                {
                    b.Property<int>("AlunoID");

                    b.Property<int>("ModalidadeID");

                    b.HasKey("AlunoID", "ModalidadeID");

                    b.HasIndex("ModalidadeID");

                    b.ToTable("AlunosModalidades");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Modalidades", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Preco");

                    b.HasKey("ID");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Pagamentos", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataPagamento");

                    b.Property<int>("IdAluno");

                    b.Property<double>("ValorPago");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdAluno");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.AlunosModalidades", b =>
                {
                    b.HasOne("Aplicacao_Kolping.Models.Alunos", "Aluno")
                        .WithMany("Modalidades")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Aplicacao_Kolping.Models.Modalidades", "Modalidade")
                        .WithMany("Alunos")
                        .HasForeignKey("ModalidadeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Aplicacao_Kolping.Models.Pagamentos", b =>
                {
                    b.HasOne("Aplicacao_Kolping.Models.Alunos", "Aluno")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
