// <auto-generated />
using Aplicacao_Kolping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplicacao_Kolping.Migrations
{
    [DbContext(typeof(Aplicacao_KolpingContext))]
    partial class Aplicacao_KolpingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aplicacao_Kolping.Models.Modalidades", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Preco");

                    b.HasKey("ID");

                    b.ToTable("Modalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
